export const CONFIGS = {
  FETCH_DATA: 'FETCH_DATA',
  UPDATA_FETCH_DATA: 'UPDATE_FETCH_DATA'
}
Object.freeze(CONFIGS)

export const AUTHEN = {
  GET: 'AUTHEN_GET',
  SAVE_DATA: 'AUTHEN_SAVE_DATA',
  LOGOUT: 'AUTHEN_LOGOUT'
}
Object.freeze(AUTHEN)

export const PATIENT = {
  GET: 'PATIENT_GET',
  EDIT: 'PATIENT_EDIT',
  ISLOADING: 'PATIENT_ISLOADING',
  ISLOADED: 'PATIENT_ISLOADED'
}
Object.freeze(PATIENT)

export const CHECKUP = {
  GETALL: 'CHECKUP_GETALL',
  LOADING: 'CHECKUP_LOADING',
  GET: 'CHECKUP_GET'
}
Object.freeze(CHECKUP)

export const ERROR_MESSAGE = {
  ERR: 'ERR',
  CODE500: 500,
  CODE404: 404,
  CODE401: 401,
  CLEAR: 'CLEAR',
  NETWORKERROR: 'NETWORKERROR'
}
Object.freeze(ERROR_MESSAGE)

export const HEADER = {
  SET: 'HEADER_SET'
}
Object.freeze(HEADER)

export const NOTIFICATION = {
  GETSOCKET: 'GETSOCKET'
}
Object.freeze(NOTIFICATION)

export const PERMISSION = {
  GET: 'GETPERMISSION'
}
Object.freeze(PERMISSION)
